// Copyright (c) Facebook, Inc. and its affiliates.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

package job

import (
	"bytes"
	"encoding/json"
	"time"

	"github.com/facebookincubator/contest/pkg/types"
)

// Report represents the report generated by ConTest
type Report struct {
	JobID      types.JobID
	Success    bool
	ReportTime time.Time
	// JobReport represents the report generated by the plugin selected in the job descriptor
	JobReport interface{}
}

// JobReportJSON marshals the report into JSON, disabling HTML escaping
func (r *Report) JobReportJSON() ([]byte, error) {
	buffer := &bytes.Buffer{}
	encoder := json.NewEncoder(buffer)
	encoder.SetEscapeHTML(false)
	err := encoder.Encode(r.JobReport)
	return buffer.Bytes(), err
}

// ReportEmitter is an interface implemented by objects that implement report emission logic
type ReportEmitter interface {
	Emit(jobReport *Report) error
}

// ReportFetcher is an interface implemented by objects that implement report fetching logic
type ReportFetcher interface {
	Fetch(jobID types.JobID) (*Report, error)
}

// ReportEmitterFetcher is an interface implemented by objects the implement report emission
// end fetching logic
type ReportEmitterFetcher interface {
	ReportEmitter
	ReportFetcher
}
